### ISSUE TITLE
Color Gradient Not Working

### ISSUE THREAD

**Issue by metkucmanic** [mokkiebear/heatmap-tracker#1]
Hello!

This is a great plugin and an improvement over the other heatmap options. With that said, I can't get the color intensity to show up in the map. I downloaded the example vault and cannot use intensityScaleStart /end to get an intensity to display. 

When I look at the example vault, it looks like there are some intensity examples for steps, but all the block look green (and are not a gradient of green). Those are Steps Tracker and Steps Tracker (11 intensities instead of 5). 

As an aside, and possibly a more complex issue, I log the time that I wake up. For dataview to understand this as a time, I log it as something like this: [Woke:: 2024-11-18T05:58]. Unfortunately, the Heatmap Calendar plugin does not recognize this as time but rather as a date and the color gradient changes per day and not time that I woke up. I have not found a better way for dataview to understand time. In addition, since this is not a number, there is no clear way to set an intensity start/stop scale. 

Thanks!

**Comment by mokkiebear** [comment]
Hi @metkucmanic,

Thank you for bringing this issue to my attention and for your detailed explanation. I truly appreciate your feedback and will investigate this as soon as possible.

Once I have more information or a solution, I will update you here promptly. Thank you for your patience in the meantime!

**Comment by mokkiebear** [comment]
Hi @metkucmanic,

Could you check please `EXAMPLE_VAULT` again please, I updated heatmaps and also added an example how to track wake up time.

<img width="692" alt="image" src="https://github.com/user-attachments/assets/91b0ad30-7d75-4fcb-810a-fe0be1ea6e15">

This is the code:
```dataviewjs

const trackerData = {
    year: 2024, // optional, remove this line to autoswitch year
    entries: [],
    colors: {
            "intensity": [
            "rgb(255, 0, 0)",
            "rgb(255, 162, 127)",
            "rgb(255, 232, 197)",
            "rgb(151, 190, 90)",
            ]
    },
    heatmapTitle: "🌅 Wake-Up Wellness Heatmap 🌅",
    heatmapSubtitle: "Track wake-up times against your target. Green means early, red means late. 🌄✨",
    intensityScaleStart: 0,
    intensityScaleEnd: 1
}

// Constants for configuration
const MAX_DIFF = 120; // Maximum time difference (in minutes) after which intensity is 0
const TARGET_TIME = "06:00"; // Target wake-up time (HH:MM format)

/**
 * Calculate the intensity of wake-up time based on the target time.
 * Intensity is 1 (best) when wake time is before or equal to the target time,
 * and decreases linearly as wake time gets later.
 *
 * @param {string} wakeTimeISO - Wake-up time in ISO format (e.g., "2024-11-18T08:30:00.000+01:00").
 * @param {string} targetTime - Target wake-up time (HH:MM format, default from constant).
 * @returns {number} Intensity value between 0 (worst) and 1 (best).
 */
function calculateIntensity(wakeTimeISO, targetTime = TARGET_TIME) {
  // Parse the wake-up time from ISO string to a Date object
  const wakeDate = new Date(wakeTimeISO);

  // Parse target time into hours and minutes
  const [targetHour, targetMinute] = targetTime.split(":").map(Number);

  // Convert target time to minutes since midnight
  const targetMinutes = targetHour * 60 + targetMinute;

  // Get wake-up time in minutes since midnight
  const wakeMinutes = wakeDate.getHours() * 60 + wakeDate.getMinutes();

  // Calculate the time difference (only if wake time is after the target time)
  const diffMinutes = Math.max(0, wakeMinutes - targetMinutes);

  // Normalize the intensity value: 1 (best) -> 0 (worst)
  return Math.max(0, 1 - diffMinutes / MAX_DIFF);
}

 
for(let page of dv.pages('"daily notes"').where(p=>p.woke)){
    trackerData.entries.push({
        date: page.file.name,
        intensity: calculateIntensity(page.woke),
        content: await dv.span(`[](${page.file.name})`)
    })  
}

renderHeatmapTracker(this.container, trackerData)

```

**Comment by mokkiebear** [comment]
I added function `calculateIntensity`.

## Explanation of the `calculateIntensity` Function

The `calculateIntensity` function computes a normalized "intensity" score based on how far a measured value (wake-up time) deviates from a target. This score is typically used to generate visual gradients for a heatmap, where higher intensity indicates better performance.

### How It Works

1. **Inputs:**
   - **`wakeTimeISO`**: The measured value to be evaluated.
   - **`targetTime`**: The desired goal to compare against.
   - Constants like **`MAX_DIFF`** determine the maximum allowable deviation after which intensity drops to zero.

2. **Normalization:**
   - The difference is normalized by dividing it by the **`MAX_DIFF`** constant.
   - The formula `1 - (diffMinutes / MAX_DIFF)` ensures:
     - Intensity is `1` when the measured value matches or precedes the target.
     - Intensity decreases linearly as the measured value deviates further from the target.

3. **Output:**
   - Returns a value between `0` and `1`:
     - `1` indicates the best performance.
     - `0` indicates the worst performance (measured value is far from the target).

**Comment by metkucmanic** [comment]
this works great! Thank you!
