### ISSUE TITLE
Feature request: Tabs configuration (show/hide)

### ISSUE THREAD

**Issue by supernrm** [mokkiebear/heatmap-tracker#15]
ability to configure tabs, for example: hide donate icon, documentation etc.

**Comment by mokkiebear** [comment]
Hello @supernrm,
Thank you for your contribution. I added tabs visibility setting in plugin settings.
<img width="900" alt="image" src="https://github.com/user-attachments/assets/84a9895f-4699-4036-b9fe-8c20b48681a8" />

Added in version **1.11.0** 🎉
